#include <stdbool.h>
#include <stdint.h>

char* basename(const char* path);
char* dirname(const char* path);
bool isalnum(char c);
bool isalpha(char c);
bool isascii(char c);
bool isblank(char c);
bool iscntrl(char c);
bool isdigit(char c);
bool isgraph(char c);
bool islower(char c);
bool isupper(char c);
bool isprint(char c);
bool ispunct(char c);
bool isspace(char c);
bool isxdigit(char c);
char tolower(char c);
char toupper(char c);
char toascii(char c);
char* strcat(char* dest, const char* src);
char* strncat(char* dest, const char* src, uint32_t n);
char* strchr(const char* str, char c);
char* strrchr(const char* str, char c);
int strcmp(const char* s1, const char* s2);
int strncmp(const char* s1, const char* s2, uint32_t n);
int strcasecmp(const char* s1, const char* s2);
int strncasecmp(const char* s1, const char* s2, uint32_t n);
char* strcpy(char* dest, const char* src);
char* strncpy(char* dest, const char* src, uint32_t n);
char* strdup(const char* str);
char* strndup(const char* str, uint32_t n);
uint32_t strlen(const char* str);
uint32_t strnlen(const char* str, uint32_t n);
char* strpbrk(const char* str, const char* accept);
char* strsep(char** str, const char* dilem);
uint32_t strspn(const char* str, const char* accept);
uint32_t strcspn(const char* str, const char* reject);
char* strstr(const char* str, const char* substr);
char* strtok_r(char* str, const char* delim, char** saveptr);
char* strtok(char* str, const char* delim);
double atof(const char* str);
int atoi(const char* str);
long atol(const char* str);
long long atoll(const char* str);
double strtod(const char* str, char** endptr);
float strtof(const char* str, char** endptr);
long strtol(const char* str, char** endptr, int base);
long long strtoll(const char* str, char** endptr, int base);
unsigned long strtoul(const char* str, char** endptr, int base);
unsigned long long strtoull(const char* str, char** endptr, int base);
int strverscmp(const char* s1, const char* s2);